apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: busybox-container
    image: busybox
    command: ['sh', '-c', 'echo Hello from BusyBox && sleep 3600']
