apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
  - name: container-1
    image: nginx:alpine
    ports:
    - containerPort: 80
  - name: container-2
    image: busybox
    command: ['sh', '-c', 'while true; do echo "Hello from Container 2" >> /usr/share/nginx/html/index.html; sleep 10; done']
